### GET all resource URLs
GET {{url}}

### GET all races
GET {{url}}/races

### GET race details (example HUMAN)
GET {{url}}/races/human

### GET race details (example ELF - has subrace)
GET {{url}}/races/elf

### GET all classes
GET {{url}}/classes

### GET class details (example WIZARD)
GET {{url}}/classes/wizard

### GET class details (example FIGHTER)
GET {{url}}/classes/fighter

### GET all ability scores
GET {{url}}/ability-scores

### GET ability score details (example STRENGTH)
GET {{url}}/ability-scores/str

### GET all traits
GET {{url}}/traits

### GET trait details (example DARKVISION)
GET {{url}}/traits/darkvision

### GET all languages
GET {{url}}/languages

### GET language details (example Elvish)
GET {{url}}/languages/elvish

### GET all subraces
GET {{url}}/subraces

### GET subrace details (example HIGH_ELF)
GET {{url}}/subraces/high-elf

### GET all feats
GET {{url}}/feats

### GET feat details (example GRAPPLER)
GET {{url}}/feats/grappler